### ISSUE TITLE
直接去爬班群里今日关于早点到的消息提取关键词是不是更准？

### ISSUE THREAD

**Issue by DusKing1** [ChaoYihu/NCU-PredictMorningCheckIn#1]

**Comment by SleepyCelery** [comment]
这里存在一个问题.
具体到当日要不要早点到,还要取决于当日凌晨的通知.
而等通知下来,就已经六点多了,离早点到不过几十分钟的时间.
而这个时候用这个做为依据去"预测"要不要早点到,意义已然不大了.
而且还存在技术上的一些问题.在今年的一月份,腾讯似乎已经关闭了所有WebQQ相关的协议,比如SmartQQ.现在除了使用第三方插件已经找不到更好的QQ机器人方案.而就算使用WebQQ,也存在不稳定的情况,很难说能不能获取到群里的通知.所以这样做可行性很低.
个人认为根据天气预测还是一个比较稳妥的方案.
我还想了一下用机器学习的方法来训练一个预测早点到的模型.但是没有足够多的带标签数据量,要累积这么多的数据,需要相当长的时间,也不太现实.
如果你有其他更好的参数来预测或者是有更好的权重参数修改方案,望能不吝讲解.或者可以直接fork这个仓库.

**Comment by DusKing1** [comment]
wine好像还有能用的
赐教？做嵌入式的赐教起来就是，做个小气象站？
py不太会

**Comment by SleepyCelery** [comment]
从传感器开始搭起的气象站吗?

**Comment by DusKing1** [comment]
对 :)

**Comment by SleepyCelery** [comment]
(σﾟ∀ﾟ)σ⁶⁶⁶⁶⁶⁶⁶⁶⁶⁶
